"""Mapping nama Country (persis seperti tertulis di kolom Country sheet CLIENT) ke IANA timezone.

Negara besar dengan banyak zona waktu (US, Australia, Russia) dipetakan ke satu zona representatif
(kota bisnis utama) - bukan akurat 100% per klien, tapi cukup buat kasarnya nentuin jam kerja lokal.
Kalau ada Country baru yang gak ada di dict ini, DO/DONT-nya di-skip (dianggap belum bisa dipastikan
jam kerjanya), BUKAN dianggap DO - biar aman, gak nge-spam di luar jam kerja beneran.
"""

COUNTRY_TIMEZONES = {
    "United Arab Emirates": "Asia/Dubai",
    "Turkey": "Europe/Istanbul",
    "Bahrain": "Asia/Bahrain",
    "India": "Asia/Kolkata",
    "Tanzania": "Africa/Dar_es_Salaam",
    "Oman": "Asia/Muscat",
    "United Kingdom": "Europe/London",
    "United States": "America/New_York",
    "Kenya": "Africa/Nairobi",
    "Qatar": "Asia/Qatar",
    "Jordan": "Asia/Amman",
    "Australia": "Australia/Sydney",
    "Pakistan": "Asia/Karachi",
    "Italy": "Europe/Rome",
    "New Zealand": "Pacific/Auckland",
    "Lebanon": "Asia/Beirut",
    "South Korea": "Asia/Seoul",
    "South Korea (Republic Of Korea)": "Asia/Seoul",
    "Kuwait": "Asia/Kuwait",
    "Saudi Arabia": "Asia/Riyadh",
    "Cyprus": "Asia/Nicosia",
    "Canada": "America/Toronto",
    "Germany": "Europe/Berlin",
    "Sri Lanka": "Asia/Colombo",
    "Japan": "Asia/Tokyo",
    "Iraq": "Asia/Baghdad",
    "Viet Nam": "Asia/Ho_Chi_Minh",
    "Vietnam": "Asia/Ho_Chi_Minh",
    "Philippines": "Asia/Manila",
    "Malaysia": "Asia/Kuala_Lumpur",
    "Singapore": "Asia/Singapore",
    "Indonesia": "Asia/Jakarta",
    "China": "Asia/Shanghai",
    "Taiwan": "Asia/Taipei",
    "Egypt": "Africa/Cairo",
    "Nigeria": "Africa/Lagos",
    "France": "Europe/Paris",
    "Spain": "Europe/Madrid",
    "Netherlands": "Europe/Amsterdam",
    "Belgium": "Europe/Brussels",
    "Poland": "Europe/Warsaw",
    "Sweden": "Europe/Stockholm",
    "Norway": "Europe/Oslo",
    "Denmark": "Europe/Copenhagen",
    "Greece": "Europe/Athens",
    "Romania": "Europe/Bucharest",
    "Israel": "Asia/Jerusalem",
    "Palestine": "Asia/Gaza",
    "Bangladesh": "Asia/Dhaka",
    "Nepal": "Asia/Kathmandu",
    "Thailand": "Asia/Bangkok",
    "Brazil": "America/Sao_Paulo",
    "Mexico": "America/Mexico_City",
    "Trinidad and Tobago": "America/Port_of_Spain",
    "Haiti": "America/Port-au-Prince",
    "Paraguay": "America/Asuncion",
    "South Africa": "Africa/Johannesburg",
    "Malta": "Europe/Malta",
    "Maldives": "Indian/Maldives",
    "Mauritius": "Indian/Mauritius",
    "Fiji": "Pacific/Fiji",
    "Georgia": "Asia/Tbilisi",
    "Bulgaria": "Europe/Sofia",
    "Czech Republic": "Europe/Prague",
    "Latvia": "Europe/Riga",
    "Lithuania": "Europe/Vilnius",
    "Slovakia": "Europe/Bratislava",
    "Kazakhstan": "Asia/Almaty",
    "Turkmenistan": "Asia/Ashgabat",
    "Ireland": "Europe/Dublin",
    "Bhutan": "Asia/Thimphu",
}


def get_timezone(country):
    return COUNTRY_TIMEZONES.get((country or "").strip())
